---
- name: Update web servers
  hosts: web
  become: yes

  tasks:
  - name: Ensure nginx Installed
    yum:
      name: nginx
      state: absent

  - name: Start nginx
    service:
      name: nginx
      state: started

  - name: Enable nginx
    service:
      name: nginx
      enabled: yes
...

