---
- hosts: all
  become: true
  tasks:
    - name: Install Nginx on Ubuntu 18.04
      apt:
        name: nginx
        state: present
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'

    - name: Install Nginx on Ubuntu 20.04
      apt:
        name: nginx
        state: present
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'
...
