---
- hosts: all
  become: true
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Install Nginx on Ubuntu
      apt:
        name: nginx
        state: absent
      when: ansible_distribution == 'Ubuntu'

    - name: Start Nginx service on Ubuntu
      service:
        name: nginx
        state: started
        enabled: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Install httpd on CentOS
      yum:
        name: httpd
        state: absent
      when: ansible_distribution == 'CentOS'

    - name: Start httpd service on CentOS
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == 'CentOS'

